BASE_URL = "https://stellarburgers.education-services.ru"
REGISTER_USER_ENDPOINT = "/api/auth/register"
LOGIN_USER_ENDPOINT = "/api/auth/login"
USER_ENDPOINT = "/api/auth/user"
INGREDIENTS_ENDPOINT = "/api/ingredients"
ORDERS_ENDPOINT = "/api/orders"